# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-28 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('show_time', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='selfboke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('show_time', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('like_num', models.IntegerField(default=0)),
                ('talk_num', models.IntegerField(default=0)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blke_id', models.IntegerField(default=0)),
                ('talk_user_id', models.IntegerField(default=0)),
                ('talk_content', models.TextField()),
                ('talk_user_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('icon', models.ImageField(upload_to='icons')),
                ('email', models.CharField(max_length=64)),
                ('u_token', models.CharField(max_length=136)),
                ('is_activite', models.BooleanField(default=False)),
                ('user_tag', models.IntegerField(default=1)),
            ],
        ),
    ]
