# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfboke',
            name='del_tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selfboke',
            name='draft_tag',
            field=models.IntegerField(default=0),
        ),
    ]
