# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181129_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forbid_talk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='resgist_time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
