# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190128_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfboke',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selfboke',
            name='talk_num',
            field=models.IntegerField(default=0),
        ),
    ]
