# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-14 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190128_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='us',
            field=models.ManyToManyField(to='blog.selfboke'),
        ),
    ]
