# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181201_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deluser_tag',
            field=models.IntegerField(default=0),
        ),
    ]
