# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_deluser_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfboke',
            name='kind_tag',
            field=models.IntegerField(default=0),
        ),
    ]
