# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_selfboke_kind_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfboke',
            name='kind_tags',
            field=models.CharField(default='散文', max_length=32),
        ),
    ]
