# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_classify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='kind_article_num',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
